### ISSUE TITLE
Fuelprice E10

### ISSUE THREAD

**Issue by monza258** [Aaron-27766/FuelPriceWidget#1]
Hi, is it possible to show Fuelprice of e10 ? 

rgds 

Grüße 🖖

**Comment by Aaron-27766** [comment]
Hi, yes it is possible. I quickly edited the file for e10 support and uploaded it as well.
Thank you for your interest in my script and I hope you enjoy using it.
Should there be complications or bugs, please let me know. I would like to help as best as I can.
Kind regards!

**Comment by monza258** [comment]
Thank you for your help. 

I really love your script.
